/*
 * Copyright (C) 2026 Codyard
 *
 * This file is part of WinBridgeAgent.
 *
 * WinBridgeAgent is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * WinBridgeAgent is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with WinBridgeAgent. If not, see <https://www.gnu.org/licenses/\>.
 */
#ifndef CLAWDESK_SETTINGS_WINDOW_IDS_H
#define CLAWDESK_SETTINGS_WINDOW_IDS_H

#define IDI_APP_ICON 100

#define IDD_SETTINGS_WINDOW 5000
#define IDC_SETTINGS_TAB 5001
#define IDC_BUTTON_APPLY 5002

#define IDC_TAB_LANGUAGE 5100
#define IDC_TAB_STARTUP 5101
#define IDC_TAB_APIKEY 5102
#define IDC_TAB_SERVER 5103
#define IDC_TAB_SECURITY 5104
#define IDC_TAB_APPEARANCE 5105
#define IDC_TAB_ABOUT 5106

#define IDC_LANGUAGE_LABEL 5200
#define IDC_LANGUAGE_COMBO 5201
#define IDC_STARTUP_CHECKBOX 5300

#define IDC_APIKEY_LABEL 5400
#define IDC_APIKEY_MASKED 5401
#define IDC_APIKEY_COPY 5402
#define IDC_APIKEY_REGEN 5403
#define IDC_APIKEY_INPUT_LABEL 5404
#define IDC_APIKEY_INPUT 5405
#define IDC_APIKEY_STATUS 5406
#define IDC_APIKEY_LINK 5407

#define IDC_SERVER_PORT_LABEL 5500
#define IDC_SERVER_PORT_INPUT 5501
#define IDC_SERVER_AUTOPORT 5502
#define IDC_SERVER_LISTEN_LABEL 5503
#define IDC_SERVER_LISTEN_ALL 5504
#define IDC_SERVER_LISTEN_LOCAL 5505
#define IDC_SERVER_STATUS_LABEL 5506
#define IDC_SERVER_UPTIME_LABEL 5507

#define IDC_SECURITY_TOKEN_LABEL 5600
#define IDC_SECURITY_TOKEN_MASKED 5601
#define IDC_SECURITY_TOKEN_REGEN 5602
#define IDC_SECURITY_ALLOWED_DIRS_LABEL 5603
#define IDC_SECURITY_ALLOWED_DIRS_LIST 5604
#define IDC_SECURITY_ALLOWED_DIRS_ADD 5605
#define IDC_SECURITY_ALLOWED_DIRS_EDIT 5606
#define IDC_SECURITY_ALLOWED_DIRS_REMOVE 5607
#define IDC_SECURITY_ALLOWED_DIRS_UP 5608
#define IDC_SECURITY_ALLOWED_DIRS_DOWN 5609
#define IDC_SECURITY_ALLOWED_APPS_LABEL 5610
#define IDC_SECURITY_ALLOWED_APPS_LIST 5611
#define IDC_SECURITY_ALLOWED_APPS_ADD 5612
#define IDC_SECURITY_ALLOWED_APPS_EDIT 5613
#define IDC_SECURITY_ALLOWED_APPS_REMOVE 5614
#define IDC_SECURITY_ALLOWED_APPS_UP 5615
#define IDC_SECURITY_ALLOWED_APPS_DOWN 5616
#define IDC_SECURITY_ALLOWED_COMMANDS_LABEL 5617
#define IDC_SECURITY_ALLOWED_COMMANDS_LIST 5618
#define IDC_SECURITY_ALLOWED_COMMANDS_ADD 5619
#define IDC_SECURITY_ALLOWED_COMMANDS_EDIT 5620
#define IDC_SECURITY_ALLOWED_COMMANDS_REMOVE 5621
#define IDC_SECURITY_ALLOWED_COMMANDS_UP 5622
#define IDC_SECURITY_ALLOWED_COMMANDS_DOWN 5623
#define IDC_SECURITY_HIGH_RISK_CHECK 5624

#define IDC_APPEARANCE_DASH_AUTO_SHOW 5700
#define IDC_APPEARANCE_ALWAYS_ON_TOP 5701
#define IDC_APPEARANCE_TRAY_STYLE_LABEL 5702
#define IDC_APPEARANCE_TRAY_STYLE_COMBO 5703
#define IDC_APPEARANCE_LOG_RETENTION_LABEL 5704
#define IDC_APPEARANCE_LOG_RETENTION_INPUT 5705
#define IDC_APPEARANCE_DAEMON_ENABLED 5706

#define IDC_ABOUT_VERSION_LABEL 5800
#define IDC_ABOUT_LICENSE_LABEL 5801
#define IDC_ABOUT_EXPIRES_LABEL 5802
#define IDC_ABOUT_OS_LABEL 5803
#define IDC_ABOUT_ARCH_LABEL 5804
#define IDC_ABOUT_DOCS_LINK 5805
#define IDC_ABOUT_SUPPORT_LINK 5806

#endif // CLAWDESK_SETTINGS_WINDOW_IDS_H
